### ISSUE TITLE
Can't get error messages when failing to create a Net::ZooKeeper client

### ISSUE THREAD

**Issue by fgabolde** [mark-5/p5-net-zookeeper#4]
In case of error messages, we usually can do:

    $zk->get_error;

to get the error message (or at least an error code).

But if we fail to create $zk at all

    my $zk = Net::ZooKeeper->new('obviously.not.going.to.work:999/whatever')
      or die "uh";

there is no indication of how to get a useful error message.

**Comment by mark-5** [comment]
The error message from a failed connect gets stored in "$!". Unfortunately, the ZooKeeper C API that Net::ZooKeeper uses only reports errors from connect attempts by setting C's errno variable(which is accessible through perl using $!, as previously mentioned).

I'd be happy to update the documentation to make this clearer.

**Comment by fgabolde** [comment]
> The error message from a failed connect gets stored in "$!". Unfortunately, the ZooKeeper C API that Net::ZooKeeper uses only reports errors from connect attempts by setting C's errno variable(which is accessible through perl using $!, as previously mentioned), which limits how descriptive the error message will be.

I see, thanks. I had examined `$!` but since all it said was "Invalid argument" I assumed it was a leftover from a previous failed operation.

> I'd be happy to update the documentation to make this clearer.

That would be great!

**Comment by mark-5** [comment]
I updated the documentation for Net::ZooKeeper::new in Net-ZooKeeper-0.40.
